version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      # uncomment this line below if you want the kafka server to run on a docker network
      # KAFKA_ADVERTISED_HOST_NAME: kafka
      # uncomment this line below if you don't want the kafka server to run on a docker network
      KAFKA_ADVERTISED_HOST_NAME: localhost

      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
# comment these lines below if you don't wan't the kafka server to run on a docker network
networks: 
  default:
    external:
      name: offtop-network

